### ISSUE TITLE
server slows to a halt

### ISSUE THREAD

**Issue by DPRsLegacy** [friendsincode/ELS-Plus#41]
everytime we have a patrol the server slows to a crawl almost stopping any plugin files to be streamed. And Only happens when more then 3 els cars are running lights.

**Comment by dexslab** [comment]
How many mods do you have installed how many vehicles do you have installed what els vehicles are you using

**Comment by M-Whitaker** [comment]
We have the same issue. When you get a large group of people to test it the whole server becomes unresponsive and unstable

**Comment by dexslab** [comment]
I need more details this is not helping me resolve the issue

**Comment by JakeRyan1** [comment]
Later today i will test ELS-Plus with a full server noting everything that goes on.

**Comment by DPRsLegacy** [comment]
Every car police and emergency services vehicle is els enabled all stock cars are replaced with custom converted models.

**Comment by JakeRyan1** [comment]
How many people are using ELS cars at the time of the crash? How many people are on the server when it goes down? What are your server specs? What is your server usage at in your task manager? Simple answers will go a long way saying one little this to describe something so big will not get solved as quickly as you want it to. It only takes longer for them to find the issue with no details.

**Comment by DPRsLegacy** [comment]
10-15 in els cars, full server when it goes down,4790k 32gb of ram, don't know CPU usage

**Comment by JakeRyan1** [comment]
When you have a full server run els again and upload the usage here

**Comment by DPRsLegacy** [comment]
Don't know if I will be able to do that

**Comment by dexslab** [comment]
I need details about the server such as mods running, artifact, els version, how many vehicles u have running how close they are to one another. Our els is mostly client sided so if your server is lagging out how many times are patterns being changed all at the same time but we are also barely sending any data back and forth between clients it's mostly just simple text of small tables

**Comment by dexslab** [comment]
Also what vehicles are you using are they properly optimized and bug free or do they have issues that cause graphical glitches sync issues or other problems

**Comment by DPRsLegacy** [comment]
Just go look up pdrp

**Comment by DPRsLegacy** [comment]
And the vehicles are fine and we're using the newest version we compiled off the GitHub project

**Comment by dexslab** [comment]
Ok and u compiled it did u make any modifications to ut

**Comment by dexslab** [comment]
Is it set to debug or release

**Comment by DPRsLegacy** [comment]
No modifications and release

**Comment by dexslab** [comment]
When I get home I will connect

**Comment by dexslab** [comment]
Your server is poorly optimized im connected and i cannot even move there is way too much crap running on it. ELS will not work properly on a poorly optimized server

**Comment by DPRsLegacy** [comment]
The server is very well optimized actually are scripts are written to slow down spawning and spamming of commands

**Comment by dexslab** [comment]
From what i have experienced so far its absolute crap. When you are in a vehicle it spams the vehicle plate OVER and OVER in console. Not to mention the spawning of police vehicles sux ass and because there is so much to download it causes your server to load really slow especially since the upload on your server sucks so bad. I mean holy shit my server on my 10Mbps uploads faster then your server does. i mean the Sheriff pack on connecting is 42 MB and it took almost 8 mins to download. I am convinced this server is defiantly poorly optimized. I pulled a max of 15 FPS on my laptop when on my server without mods i get 30 and on an RP server i belong to i get 28-35 depending on location.

**Comment by dexslab** [comment]
I mean for fucks sake not even the UI is working properly which tells me something is definately wrong

**Comment by DPRsLegacy** [comment]
That happened when we installed the els script

**Comment by dexslab** [comment]
I guarentee you that stock FiveM with ELS alone does not run that way. I play on Dead Zone RP we have over 20 different els vehicles installed over 50 mods and no issues with more then 10 people on the server. I know it is not ELS due to the fact that ELS does not spam console unless needed let alone other stuff. please take a hard look at what you are running on  your server that could be causing the issues ELS is not the only problem you have Hell i could barely connect to your server as it is

**Comment by dexslab** [comment]
[CitizenFX.log](https://github.com/ejb1123/ELS-Plus/files/1721507/CitizenFX.log)
There is the Client log when i was logged into your server on my good rig. As you can see there is WAY to much spam in the logs for no reason not to mention the continuous downloading of various streamed resources. This causes major sluggishness.

**Comment by DPRsLegacy** [comment]
The plate spam is our fault I will have to talk to the guy who made the script and let me pull a log from a server member to compare to

**Comment by dexslab** [comment]
This issue should be fixed in https://github.com/friendsincode/ELS-Plus/pull/45

**Comment by dexslab** [comment]
This issue has most definitely been resolved
